jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: vars
      name: Set output
      run: 'echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      id: check
      name: checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build inrt template
      run: 'chmod 777 ./gradlew

        ./gradlew app:buildTemplateApp

        '
    - continue-on-error: true
      name: Build App
      run: './gradlew app:assembleV6

        '
    - continue-on-error: true
      env:
        BUILD_TOOLS_VERSION: 34.0.0
      name: Sign app APK
      uses: Tlaster/android-sign@v1.2.2
      with:
        alias: ${{ secrets.AALIAS }}
        keyPassword: ${{ secrets.AKEY_PASSWORD }}
        keyStorePassword: ${{ secrets.AKEY_STORE_PASSWORD }}
        output: build/app/signed
        releaseDirectory: 'app/build/outputs/apk/v6/release

          '
        signingKeyBase64: ${{ secrets.ASIGNING_KEY }}
    - continue-on-error: true
      name: rename apk
      run: 'cd build/app/signed

        mv app-v6-arm64-v8a-*.apk Autox-v6-arm64-v8a-release-${{steps.vars.outputs.short_ref}}.apk

        mv app-v6-armeabi-v7a-*.apk Autox-v6-armeabi-v7a-release-${{steps.vars.outputs.short_ref}}.apk

        mv app-v6-universal-*.apk Autox-v6-universal-release-${{steps.vars.outputs.short_ref}}.apk

        ls

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.repository == 'kkevsekk1/AutoX'
      name: create-gh-release
      uses: taiki-e/create-gh-release-action@v1
      with:
        changelog: CHANGELOG.md
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/')
      name: create-release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/signed/**
    - continue-on-error: true
      if: github.repository == 'kkevsekk1/AutoX'
      name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
        endpoint: oss-cn-hangzhou.aliyuncs.com
    - continue-on-error: true
      if: github.repository == 'kkevsekk1/AutoX'
      name: update apk to aliyun
      run: 'ossutil mkdir oss://autoxjsoss/autoxjs/${{ steps.vars.outputs.short_ref
        }}

        ossutil cp -rf build/app/signed oss://autoxjsoss/autoxjs/${{ steps.vars.outputs.short_ref
        }}

        '
name: Android CI build
on:
  repository_dispatch:
    types: trigger-ga___android.yml
