jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v5
      with:
        close-issue-message: "\u6B64lssue\u7531\u4E8E\u957F\u671F\u672A\u6D3B\u52A8\
          \u5DF2\u88AB\u81EA\u52A8\u5173\u95ED\uFF0C\u5982\u95EE\u9898\u4EFB\u7136\
          \u5B58\u5728\uFF0C\u8BF7\u91CD\u65B0\u6253\u5F00lssue"
        close-pr-message: "\u6B64pr\u7531\u4E8E\u957F\u671F\u672A\u6D3B\u52A8\u5DF2\
          \u88AB\u81EA\u52A8\u5173\u95ED"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: "\u65E0\u6D3B\u52A8"
        stale-pr-label: "\u65E0\u6D3B\u52A8"
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
